services:
  backend:
    build: ./Backend
    container_name: PIN_backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mi_db
      - SPRING_DATASOURCE_USERNAME=usuario
      - SPRING_DATASOURCE_PASSWORD=clave
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - MULTIMEDIA_DIR=/multimedia
      - MQTT_BROKER=tcp://mqtt:1883
    volumes:
      - ./multimedia:/multimedia
    depends_on:
      - db
      - mqtt

  db:
    image: postgres:16
    container_name: PIN_db
    environment:
      POSTGRES_DB: mi_db
      POSTGRES_USER: usuario
      POSTGRES_PASSWORD: clave
    volumes:
      - ./db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mqtt:
    image: eclipse-mosquitto:2.0.22
    container_name: PIN_MQTT
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/data:/mosquitto/data:rw
      - ./mosquitto/logs:/mosquitto/logs:rw