# Escucha en todas las interfaces de red, no solo 'localhost'
listener 1883 0.0.0.0

# Permite que el backend y el healthcheck se conecten sin contraseña
allow_anonymous true

# (Opcional) Habilita el puerto de WebSockets para el frontend
listener 9001
protocol websockets