spring.application.name=backend
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/mi_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:usuario}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:clave}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}

multimedia.dir=${MULTIMEDIA_DIR:/app/multimedia}