name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:15
        env:
          POSTGRES_USER: usuario
          POSTGRES_PASSWORD: clave
          POSTGRES_DB: mi_db
        ports:
          - 5432:5432
        # volumes:
          # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        options: >-
          --health-cmd="pg_isready -U testuser -d testdb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Wait for DB
        run: |
          for i in {1..30}; do
            nc -z localhost 5432 && echo "DB is up!" && break
            echo "Waiting for db..."
            sleep 2
          done

      - name: Run tests
        run: cd Backend && mvn test
